== SimpleTest Documentation UI

The SimpleTest project leverages Antora for documentation management.
This repository provides the user interface for the project documentation.
The UI project is named simpletest-docs-ui.
It is based on antora-ui-default and has been fully customized and extended
to meet the requirements of SimpleTest.

=== Commands

- List all commands: `npx gulp --tasks`

- To clean up: `npx gulp clean`

- To build the build the assets (css, js, fonts, etc) into the folder `/public/_`:

`npx gulp build`

- To view the output folders of generated assets:

```
ls -la public/_/js
ls -la public/_/css
ls -la public/_/font
```

- To build the preview site (html) into the folder `/public`:

`npx gulp preview:build`

- To view the output folder of the generated site:

```
ls -la public

```

- To package the ui-bundle for Antora:

`npx gulp bundle`

IMPORTANT: The build order is important. Because the `bundle` step calls the `clean` step internally (to get rid of any html and only bundle the assets). Publish before bundling! See .github/workflows/publish-pages.yml for details.

- To start the dev server: `LIVERELOAD=1 npx gulp preview`
